### ISSUE TITLE
Get displayed time function

### ISSUE THREAD

**Issue by Larney11** [michaeljstevens/react-native-stopwatch-timer#1]
I am working on an app where the stopwatch time must be stored to the database.
Is it possible to get the time that is displayed in the stopwatch?

**Comment by waterdoo** [comment]
+1

**Comment by joaom182** [comment]
+1

**Comment by lucasfugisawa** [comment]
+1

**Comment by michaeljstevens** [comment]
The new version has getTime prop. Could also pass time to the handleFinish function. Wasn't sure which is better. Let me know.

**Comment by GavinThomas1192** [comment]
How can we store laps? or use the time prop from getTime? Can you post an example of storing the time at lets say a button click?

**Comment by JZorina** [comment]
did you manage to handle this? @michaeljstevens
