### ISSUE TITLE
Set timer

### ISSUE THREAD

**Issue by runeogod** [michaeljstevens/react-native-stopwatch-timer#11]
Hello, thanks for this package.

Is there a where to specify what time to start the timer ? 

like start from 01:22:00 instead of 00:00:00

Thanks.

Regards

**Comment by hari-mohan-choudhary** [comment]
@runeogod  I am looking same thing so have resolved issue

**Comment by tvhimanshu** [comment]
@michaeljstevens - I am also looking for same enhancements, do we have any update on this?

**Comment by michaeljstevens** [comment]
there's now a startTime prop for the stopwatch

**Comment by MssMaster** [comment]
@michaeljstevens I am using a startTime prop but timer did not start from a particular time it always starts from '00:00:00'.I am using  "react-native-stopwatch-timer": "0.0.20" version.

I passed milliseconds in startTime prop. Please guide me on what we are doing wrong?
