### ISSUE TITLE
Bug display, react-native v 0.53

### ISSUE THREAD

**Issue by mylimdescho** [michaeljstevens/react-native-stopwatch-timer#12]
Hello,

I'm using the code in the example (without the timer, only the stopwatch, and after 1 sec I got this weird bug with negative numbers replacing the normals numbers.

![bug](https://user-images.githubusercontent.com/16938832/37595683-f634eeca-2b79-11e8-9118-73783d815732.png)

I'm on react-native 0.53, the code is the same as the example

**Comment by zayedelfasa** [comment]
please tell me how to fix this. I have a same issue with him. thank you..

**Comment by alexandercyr** [comment]
try this out. I was getting a similar error when I start and stop and start again. this fixed that issue for me.
[https://github.com/michaeljstevens/react-native-stopwatch-timer/issues/8](url)

**Comment by michaeljstevens** [comment]
added this fix
