### ISSUE TITLE
timer minutes

### ISSUE THREAD

**Issue by sure1243jupiter** [michaeljstevens/react-native-stopwatch-timer#15]
hi there it is better to get the individual seconds and minutes from getTime instead of getting a formatted value from it

**Comment by janguck** [comment]
how get?

**Comment by michaeljstevens** [comment]
@sure1243jupiter latest version includes getMsecs function

**Comment by michaeljstevens** [comment]
@johnlow95 duplicate of #18

**Comment by shubhamtechvalens** [comment]
@michaeljstevens I am using getMsecs function to get the time. Can you please help me with accessing value outside the function?

I am using just like this:

  getFormattedTime (time) {
    if (time !== 0) {
      this.milliSeconds = time
      console.log('getFormattedTime', this.milliSeconds)
    }
  }

just after this method variable milliSeconds reset to its initial value i.e. 0.
How can i access milliSeconds outside getFormattedTime?
