### ISSUE TITLE
Stopping the stopwatch does not stop counting the time

### ISSUE THREAD

**Issue by lucasfugisawa** [michaeljstevens/react-native-stopwatch-timer#4]
Stopping the stopwatch does not stop counting the time. When you start the stopwatch again, it does not resume from the time it stopped. Instead, 

Example scenario based on the TestApp example you provided:
- Start the stopwatch.
- Click "Stop" to stop the stopwatch on 00:00:05:00.
- Leave it stopped and wait about 10 seconds.
- Click "Start" to resume the stopwatch.

Expected stopwatch behavior: The stopwatch resumes from 00:00:05:000.
Actual behavior: The stopwatch resumes from about 00:00:15:000.

**Comment by semammerlaan** [comment]
If you add the prop 'laps' it works like you want

**Comment by michaeljstevens** [comment]
thanks for pointing out @lucasfugisawa. Should be fixed in new release
