### ISSUE TITLE
Is there a way to reset and start in one setState() call?

### ISSUE THREAD

**Issue by gotoAndBliss** [michaeljstevens/react-native-stopwatch-timer#5]
Hey amazing git! Really appreciate your work.

I'm looking to reset and start the stopwatchTimer in one call. But it seems this doesn't work.

```
  componentDidUpdate(prevProps, prevState) {
  if ( some conditions ) {
       this.resetStopWatchTimer()
       this.setStopwatch();
//////

  }
  setStopwatch() {
    this.setState({stopwatchStart: true, stopwatchReset: false});
  };
  resetStopWatchTimer() {
    this.setState({stopwatchStart: false, stopwatchReset: true});
  }; 
```
In this case, it just keeps ticking.

Then I tried to do something inbetween like this

```
this.setState({stopwatchStart: true, stopwatchReset: true)}
```
And I think this "technically" works, but the stopwatch timer then loses its formatted time styling.

Anyways, I was curious what you think. I would be more than happy to contribute a fork if you think there's something missing here. I'm hoping for the chance that I'm actually just being dumb and there's a better way to do it. 👍

**Comment by gotoAndBliss** [comment]
I resolved this by using `props` instead of `state`. Thanks again for the amazing work!

**Comment by b3tts32** [comment]
@gotoAndBliss can you share your code for this? I'm running into the same issue. Thanks!
