### ISSUE TITLE
Issue with stop and start fixed by this LINE 69

### ISSUE THREAD

**Issue by Ballak-T** [michaeljstevens/react-native-stopwatch-timer#8]
```
    this.interval = this.interval ? this.interval : setInterval(() => {
        this.setState({elapsed: new Date() - this.state.startTime });
    }, 1);
  }
```
**this.state.pausedTime** deleted

**Comment by alexandercyr** [comment]
perfect! solved issue for me.

**Comment by zayedelfasa** [comment]
thank you!

**Comment by hungdev** [comment]
it seems not to work for me. So I decided to code myself.

**Comment by Ballak-T** [comment]
@hungdev Maybe there was an update which destroyed this solution. Or make sure that everytime you do yarn / yarn upgrade, you also run script that overrides module with changes you want.

**Comment by rangellucas** [comment]
just change this line on file:  lib/stopwatch.js
from
 this.setState({elapsed: new Date() - this.state.startTime - this.state.pausedTime });
to
this.setState({elapsed: new Date() - this.state.startTime });

remove this.state.pausedTime as mentioned above.

**Comment by michaeljstevens** [comment]
thanks 👍 added this fix
